### ISSUE TITLE
Progress bar says it is downloading but in the download folders are only a few downloaded images/videos

### ISSUE THREAD

**Issue by coldfax** [ToTheMax/Snapchat-All-Memories-Downloader#2]
Hello there,

First wanted to say, thank you so much for uploading this little tool. It has been driving me crazy for years that you can't mass export from their platform.

Basically as the title says, the progress bar says it is downloading but the downloads stops somewhere but the progress bar continues. I have a feeling Snapchat has some kind of timeout on concurrent downloads or something of that nature. I tried lowering the concurrent downloads to 10 but the same thing happens. It seems like if the video/photo in question is a large size and takes a while to download, it will download them but by the time they are fully downloaded, I noticed the progress bar is already passed those initial 10 downloads and so it does not continue downloading other files. I really hope this make sense because it's hard to explain.

Is there a way to add a pause for it to take 2-3mins before initiating the next 10 downloads? I thought that's what the concurrency argument does but it doesn't seem so.

Thank you.

**Comment by ToTheMax** [comment]
Hi coldfax!

When you set the number of concurrent requests to 10, the script makes sure there are never more then 10 downloads at a time. 

When a download finished, it immediately starts a new download, but never more than 10 at a time. So these downloads aren't done in batches of 10 like you suggest, but continuously.

A large video can take a while, but in the meantime tens of other pictures will be downloaded.

Did you wait for the script to complete? The last few percentages can take a while since these will probably be the larger files, are there any failed downloads?

To test you can also lower the concurrent downloads to 1.

Finally, I found out that these downloadlinks will eventually expire, so it's always best to test with a fresh requested zip!

**Comment by ToTheMax** [comment]
Ah I ran the script myself and see the problem you are describing, weird, it worked before. 
I will let you know when I fixed it!

**Comment by ToTheMax** [comment]
Could you check again? Should be fixed now!

**Comment by coldfax** [comment]
Yep! It is working now. Great job and thanks again. Will spread this to my friends as well as I know quite a few people who would be interested.

**Comment by ToTheMax** [comment]
Cool! Feel free to share & star this Repo!
