### ISSUE TITLE
I ran out of space

### ISSUE THREAD

**Issue by masahiiko1** [ToTheMax/Snapchat-All-Memories-Downloader#34]
How do I continue the download if I ran out of space?

**Comment by ToTheMax** [comment]
The only way would be to remove the lines from `memories.json` that already have been downloaded

**Comment by TheTechRobo** [comment]
Any chance of you adding an auto-continuation feature? My computer fell asleep and it's stuck...

![image](https://user-images.githubusercontent.com/52163910/126882888-ae847f92-b26d-4ab3-b48b-a1cb8879db1a.png)

**Comment by ToTheMax** [comment]
I can add a check whether a filename already exists but the problem is that some pictures/videos might not have been fully downloaded, I don't think there is a way to check if they are. So then you can end up with #number_of_concurrent_connections incomplete pictures/videos

**Comment by TheTechRobo** [comment]
Ah, that sucks.

What about having a manifest sort of thing like `tar` where files are added to the list every time it's complete? Something like:

```bash
$ node main.js --incremental file_list.txt
CDN-LINKS: [====================] 12414/12414   Failed: 0
DOWNLOADS: [==========----------] 6756/12414    Failed: 1
^C
$ node main.js --incremental file_list.txt
Incremental download: Starting from download 6756
CDN-LINKS: [====================] 12414/12414   Failed: 0
DOWNLOADS: [==========----------] 6756/12414    Failed: 1
```

(By the way, does this script retry on error? That Failed: 1 is worrying me that I'll have an incomplete archive. Datahoarder I know :P)

**Comment by TheTechRobo** [comment]
I might be able to work on it, but the code will be uglier than me because I don't know JavaScript very well :P

**Comment by ToTheMax** [comment]
I have been thinking how to fix this. There might be cleaner ways then holding a list of downloaded files. First we can check whether a filename already exists in the folder, then there are different ways to check if the file download really completed:

### 1) Check JPEG completeness
I think I found a way to see whether a jpeg is complete or not, by checking the endbytes:
- Bytes: https://stackoverflow.com/a/4585611/7334699 
- Implementation (we need to check endbyte instead): https://github.com/foxbit19/valid-jpeg/blob/master/index.js

 ### 2) Check MP4 completeness
This gets harder for mp4's since they dont have a particular endbyte. However, they do have certain metadata which can reveal information whether a file is complete or not. The following metadata fields (checked on [metadata2go.com](https://www.metadata2go.com/)) might be important for a complete video vs a incomplete video:

Meta Header | Complete | Incomplete
--- | --- | ---
Size | 2462263 | 94772
Media Data Size | 2455027 | 2455027
Bit Rate | 2462263 | 131193
Warning |  | Truncated 'mdat' data

  - `Size`: 94772 vs 2462263
  - `Media Data Size`: 2455027 vs 2455027
  - `Bit Rate`: 131193 vs 2462263
  - `Warning`:  "Truncated 'mdat' data" vs  no warning
  
### 3) Check FILE creation date
This is probably the easiest way: this script updates the creation date of a file once the entire download is finished. So you can just check whether the file creation date matches the media date we retrieved from snapchat to see if the download has finished.

If you have time, feel free to implement something like this! Nice way to learn some JS :)
If you can't figure it out, I might be able to work on it later this week.

**Comment by TheTechRobo** [comment]
I think we should check the modified date instead; birthtime isn't always stored on Linux (as you noted in the script).
